# Generated by Django 4.2.7 on 2023-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_user_post_author_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
    ]
